export const HOME = '/'
export const AUTH = '/auth'
export const REGISTER = '/register'
export const PROFILE = '/profile'
export const ROADMAP = '/roadmap/:chapterName'
export const NOT_FOUND = '/not_found'
export const ERROR = '*'
